const users =
    [
        {
            "nome": "Mirella Francisca Lara Duarte",
            "idade": 36,
            "cpf": "29656122623",
            "rg": "170072502",
            "data_nasc": "26/05/1987",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Elza Nicole",
            "pai": "Emanuel Levi Duarte",
            "email": "mirellafranciscaduarte@lojasrayton.com",
            "senha": "CfrDdauli1",
            "cep": "97502036",
            "endereco": "Rua Sete de Setembro",
            "numero": 282,
            "bairro": "Mascarenhas de Moraes",
            "cidade": "Uruguaiana",
            "estado": "RS",
            "telefone_fixo": "5537371009",
            "celular": "55985243168",
            "altura": "1,84",
            "peso": 48,
            "tipo_sanguineo": "B+",
            "cor": "vermelho"
        },
        {
            "nome": "Lara Tânia Costa",
            "idade": 45,
            "cpf": "17285207896",
            "rg": "140358134",
            "data_nasc": "14/06/1978",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Adriana Olivia Luna",
            "pai": "Manoel Alexandre Costa",
            "email": "larataniacosta@outlook.com",
            "senha": "4nOUbna705",
            "cep": "59062490",
            "endereco": "Vila Matoso",
            "numero": 763,
            "bairro": "Lagoa Nova",
            "cidade": "Natal",
            "estado": "RN",
            "telefone_fixo": "8439755206",
            "celular": "84987187508",
            "altura": "1,79",
            "peso": 86,
            "tipo_sanguineo": "B+",
            "cor": "verde"
        },
        {
            "nome": "Henrique Felipe Barbosa",
            "idade": 43,
            "cpf": "65668886832",
            "rg": "470375838",
            "data_nasc": "14/01/1980",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Daniela Emilly",
            "pai": "Bernardo Enzo Barbosa",
            "email": "henrique-barbosa90@operaconstrutora.com.br",
            "senha": "NpqcAUgIYK",
            "cep": "79012511",
            "endereco": "Rua Fanny",
            "numero": 785,
            "bairro": "Bosque de Avilan",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6729592073",
            "celular": "67983690997",
            "altura": "1,95",
            "peso": 82,
            "tipo_sanguineo": "AB+",
            "cor": "amarelo"
        },
        {
            "nome": "Gustavo Elias Emanuel Assis",
            "idade": 50,
            "cpf": "10423757989",
            "rg": "218104923",
            "data_nasc": "14/06/1973",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Maya Sandra Isabel",
            "pai": "Thomas Renato Assis",
            "email": "gustavo_assis@viasegbrasil.com.br",
            "senha": "4TjtHqQyT9",
            "cep": "49044566",
            "endereco": "Rua C",
            "numero": 644,
            "bairro": "Santa Maria",
            "cidade": "Aracaju",
            "estado": "SE",
            "telefone_fixo": "7939371985",
            "celular": "79993359517",
            "altura": "1,71",
            "peso": 109,
            "tipo_sanguineo": "A+",
            "cor": "vermelho"
        },
        {
            "nome": "Giovanna Jéssica Andreia Baptista",
            "idade": 72,
            "cpf": "42846483906",
            "rg": "330382858",
            "data_nasc": "22/05/1951",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Beatriz Evelyn Helena",
            "pai": "Marcos Vinicius Pedro Henrique Baptista",
            "email": "giovannajessicabaptista@silicotex.net",
            "senha": "gsSymzMYne",
            "cep": "57040500",
            "endereco": "Rua Santo Antônio",
            "numero": 618,
            "bairro": "Jacintinho",
            "cidade": "Maceió",
            "estado": "AL",
            "telefone_fixo": "8236263371",
            "celular": "82994716590",
            "altura": "1,71",
            "peso": 82,
            "tipo_sanguineo": "A+",
            "cor": "vermelho"
        },
        {
            "nome": "Otávio Erick José da Conceição",
            "idade": 53,
            "cpf": "63296357300",
            "rg": "273501756",
            "data_nasc": "05/06/1970",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Melissa Larissa",
            "pai": "Leandro Isaac Raul da Conceição",
            "email": "otavioerickdaconceicao@greenschool.com.br",
            "senha": "BibFe0o8JG",
            "cep": "25902696",
            "endereco": "Rua Três",
            "numero": 823,
            "bairro": "Citrolândia",
            "cidade": "Magé",
            "estado": "RJ",
            "telefone_fixo": "2127343783",
            "celular": "21994868189",
            "altura": "1,61",
            "peso": 92,
            "tipo_sanguineo": "B+",
            "cor": "laranja"
        },
        {
            "nome": "Vitor Julio da Rosa",
            "idade": 58,
            "cpf": "13235533397",
            "rg": "276295365",
            "data_nasc": "08/06/1965",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Isabelly Laura Lavínia",
            "pai": "Raul Henrique Cauã da Rosa",
            "email": "vitor-darosa94@hotelruby.com.br",
            "senha": "dR8pFe59By",
            "cep": "28060520",
            "endereco": "Rua Vinte de Janeiro",
            "numero": 882,
            "bairro": "Parque Aldeia",
            "cidade": "Campos dos Goytacazes",
            "estado": "RJ",
            "telefone_fixo": "2239220582",
            "celular": "22995091565",
            "altura": "1,77",
            "peso": 82,
            "tipo_sanguineo": "A-",
            "cor": "amarelo"
        },
        {
            "nome": "Luiz Raul Bernardes",
            "idade": 48,
            "cpf": "25461442005",
            "rg": "506702431",
            "data_nasc": "03/05/1975",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Daniela Lorena",
            "pai": "Luís Alexandre Bernardes",
            "email": "luiz_bernardes@fabiooliva.com.br",
            "senha": "uziqIPmjbW",
            "cep": "79083357",
            "endereco": "Rua Tubergia",
            "numero": 296,
            "bairro": "Jardim das Hortências",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6739275100",
            "celular": "67985120466",
            "altura": "1,60",
            "peso": 99,
            "tipo_sanguineo": "A-",
            "cor": "amarelo"
        },
        {
            "nome": "Erick Martin Joaquim Moraes",
            "idade": 54,
            "cpf": "49211793106",
            "rg": "420410363",
            "data_nasc": "16/02/1969",
            "sexo": "Masculino",
            "signo": "Aquário",
            "mae": "Julia Heloisa Natália",
            "pai": "Kevin Luan Heitor Moraes",
            "email": "erick_moraes@yazigi.com",
            "senha": "xlxLIaW1hU",
            "cep": "59158228",
            "endereco": "Rua Índia",
            "numero": 815,
            "bairro": "Parque das Nações",
            "cidade": "Parnamirim",
            "estado": "RN",
            "telefone_fixo": "8438921036",
            "celular": "84989553764",
            "altura": "1,75",
            "peso": 74,
            "tipo_sanguineo": "B+",
            "cor": "azul"
        },
        {
            "nome": "Gael Igor Vieira",
            "idade": 26,
            "cpf": "73931265676",
            "rg": "267214972",
            "data_nasc": "02/01/1997",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Olivia Sueli",
            "pai": "César Felipe Luan Vieira",
            "email": "gael_igor_vieira@gruposimoes.com.br",
            "senha": "OFP8lYu1bB",
            "cep": "83325120",
            "endereco": "Rua Píen",
            "numero": 352,
            "bairro": "Emiliano Perneta",
            "cidade": "Pinhais",
            "estado": "PR",
            "telefone_fixo": "4129771105",
            "celular": "41997152797",
            "altura": "1,84",
            "peso": 92,
            "tipo_sanguineo": "O-",
            "cor": "vermelho"
        },
        {
            "nome": "Roberto Leonardo Lopes",
            "idade": 26,
            "cpf": "31426457308",
            "rg": "380422736",
            "data_nasc": "15/03/1997",
            "sexo": "Masculino",
            "signo": "Peixes",
            "mae": "Bianca Isabel",
            "pai": "Breno Manoel Anthony Lopes",
            "email": "roberto-lopes94@dvdja.com.br",
            "senha": "yrDyR4kObj",
            "cep": "79021110",
            "endereco": "Rua das Garças",
            "numero": 385,
            "bairro": "Santa Fé",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6726058536",
            "celular": "67985411555",
            "altura": "1,69",
            "peso": 108,
            "tipo_sanguineo": "AB+",
            "cor": "amarelo"
        },
        {
            "nome": "Rayssa Eliane Almeida",
            "idade": 70,
            "cpf": "87102780362",
            "rg": "433075752",
            "data_nasc": "05/01/1953",
            "sexo": "Feminino",
            "signo": "Capricórnio",
            "mae": "Laura Vera",
            "pai": "Alexandre César Luís Almeida",
            "email": "rayssaelianealmeida@devuono.com.br",
            "senha": "Ah3rOcukRL",
            "cep": "11662600",
            "endereco": "Avenida Vítor Meirelles",
            "numero": 587,
            "bairro": "Martim de Sá",
            "cidade": "Caraguatatuba",
            "estado": "SP",
            "telefone_fixo": "1238361061",
            "celular": "12993564434",
            "altura": "1,83",
            "peso": 55,
            "tipo_sanguineo": "O-",
            "cor": "amarelo"
        },
        {
            "nome": "Julio Guilherme Edson Nogueira",
            "idade": 45,
            "cpf": "15848392609",
            "rg": "230539142",
            "data_nasc": "24/05/1978",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Milena Fátima Nair",
            "pai": "Iago Pedro Henrique Nelson Nogueira",
            "email": "julioguilhermenogueira@acesse.net",
            "senha": "JT6TYPfeTw",
            "cep": "69915888",
            "endereco": "Rua Maritê",
            "numero": 402,
            "bairro": "Portal da Amazônia",
            "cidade": "Rio Branco",
            "estado": "AC",
            "telefone_fixo": "6827119992",
            "celular": "68992942084",
            "altura": "1,71",
            "peso": 95,
            "tipo_sanguineo": "A+",
            "cor": "vermelho"
        },
        {
            "nome": "Martin Gustavo Renan Fernandes",
            "idade": 68,
            "cpf": "59362312751",
            "rg": "272237681",
            "data_nasc": "10/01/1955",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Eduarda Elza",
            "pai": "Thomas Eduardo Fernandes",
            "email": "martin-fernandes71@trt15.jus.br",
            "senha": "egsBFyQ4JQ",
            "cep": "35170556",
            "endereco": "Rua Seis",
            "numero": 622,
            "bairro": "José da Silva Brito",
            "cidade": "Coronel Fabriciano",
            "estado": "MG",
            "telefone_fixo": "3137758627",
            "celular": "31992713625",
            "altura": "1,85",
            "peso": 67,
            "tipo_sanguineo": "A+",
            "cor": "azul"
        },
        {
            "nome": "Vitor Arthur Lucca Brito",
            "idade": 73,
            "cpf": "91565598601",
            "rg": "124961496",
            "data_nasc": "01/01/1950",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Mariane Rosângela Márcia",
            "pai": "Davi Davi Brito",
            "email": "vitor.arthur.brito@viamoc.com.br",
            "senha": "REz0qBCbty",
            "cep": "06620385",
            "endereco": "Alameda Manhantan",
            "numero": 826,
            "bairro": "Parque Nova Jandira",
            "cidade": "Jandira",
            "estado": "SP",
            "telefone_fixo": "1125844271",
            "celular": "11994304737",
            "altura": "1,76",
            "peso": 73,
            "tipo_sanguineo": "AB-",
            "cor": "amarelo"
        },
        {
            "nome": "Ricardo Marcelo Marcos Cavalcanti",
            "idade": 59,
            "cpf": "12858970211",
            "rg": "287453303",
            "data_nasc": "12/03/1964",
            "sexo": "Masculino",
            "signo": "Peixes",
            "mae": "Silvana Lorena Kamilly",
            "pai": "Isaac Julio Isaac Cavalcanti",
            "email": "ricardo_marcelo_cavalcanti@amoamar.com.br",
            "senha": "YTkTty00ZY",
            "cep": "59040282",
            "endereco": "Vila Coronel José Bernardo",
            "numero": 236,
            "bairro": "Alecrim",
            "cidade": "Natal",
            "estado": "RN",
            "telefone_fixo": "8436566944",
            "celular": "84996766848",
            "altura": "1,92",
            "peso": 90,
            "tipo_sanguineo": "AB-",
            "cor": "amarelo"
        },
        {
            "nome": "Thiago Nathan Melo",
            "idade": 35,
            "cpf": "93246855110",
            "rg": "147366550",
            "data_nasc": "07/06/1988",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Clarice Luciana",
            "pai": "César Kevin Melo",
            "email": "thiago_melo@bom.com.br",
            "senha": "ZHBUQyyLbo",
            "cep": "69088247",
            "endereco": "Beco Parada Angélica",
            "numero": 860,
            "bairro": "Jorge Teixeira",
            "cidade": "Manaus",
            "estado": "AM",
            "telefone_fixo": "9237292621",
            "celular": "92985496917",
            "altura": "1,88",
            "peso": 97,
            "tipo_sanguineo": "O-",
            "cor": "roxo"
        },
        {
            "nome": "Nair Teresinha Cardoso",
            "idade": 32,
            "cpf": "21298559707",
            "rg": "122383060",
            "data_nasc": "21/04/1991",
            "sexo": "Feminino",
            "signo": "Touro",
            "mae": "Regina Sarah Alícia",
            "pai": "Felipe Igor Renato Cardoso",
            "email": "nair-cardoso80@novadeliveri.com.br",
            "senha": "p5uNsAh6c9",
            "cep": "64006430",
            "endereco": "Rua Dez",
            "numero": 112,
            "bairro": "Água Mineral",
            "cidade": "Teresina",
            "estado": "PI",
            "telefone_fixo": "8626152955",
            "celular": "86983976198",
            "altura": "1,55",
            "peso": 58,
            "tipo_sanguineo": "O+",
            "cor": "vermelho"
        },
        {
            "nome": "Priscila Lívia Novaes",
            "idade": 65,
            "cpf": "95954337217",
            "rg": "349013421",
            "data_nasc": "12/05/1958",
            "sexo": "Feminino",
            "signo": "Touro",
            "mae": "Hadassa Eliane Fabiana",
            "pai": "Augusto Rafael Novaes",
            "email": "priscila-novaes86@delfrateinfo.com.br",
            "senha": "qP9MLzoObl",
            "cep": "59160904",
            "endereco": "Avenida Alphaville 391",
            "numero": 559,
            "bairro": "Pium (Distrito Litoral)",
            "cidade": "Parnamirim",
            "estado": "RN",
            "telefone_fixo": "8436558827",
            "celular": "84999335218",
            "altura": "1,68",
            "peso": 71,
            "tipo_sanguineo": "B+",
            "cor": "preto"
        },
        {
            "nome": "Maria Alana Antonella Fogaça",
            "idade": 35,
            "cpf": "55219845500",
            "rg": "488958891",
            "data_nasc": "27/04/1988",
            "sexo": "Feminino",
            "signo": "Touro",
            "mae": "Cristiane Márcia Mariah",
            "pai": "Luiz Manuel Fernando Fogaça",
            "email": "mariaalanafogaca@yahoo.com.com.br",
            "senha": "fcWhDzmcB6",
            "cep": "58421355",
            "endereco": "Rua Luiz Ferreira da Silva",
            "numero": 430,
            "bairro": "Acácio Figueiredo",
            "cidade": "Campina Grande",
            "estado": "PB",
            "telefone_fixo": "8327647206",
            "celular": "83997637234",
            "altura": "1,82",
            "peso": 59,
            "tipo_sanguineo": "O+",
            "cor": "vermelho"
        },
        {
            "nome": "Mário Nelson da Mata",
            "idade": 61,
            "cpf": "86014072772",
            "rg": "327757887",
            "data_nasc": "12/04/1962",
            "sexo": "Masculino",
            "signo": "Áries",
            "mae": "Ayla Antônia Josefa",
            "pai": "Gabriel Eduardo da Mata",
            "email": "marionelsondamata@metraseg.com.br",
            "senha": "mkJzKRQrf3",
            "cep": "90843420",
            "endereco": "Beco Oito",
            "numero": 936,
            "bairro": "Nonoai",
            "cidade": "Porto Alegre",
            "estado": "RS",
            "telefone_fixo": "5125217510",
            "celular": "51993454701",
            "altura": "1,85",
            "peso": 60,
            "tipo_sanguineo": "A+",
            "cor": "roxo"
        },
        {
            "nome": "Rosângela Sophia Cláudia Pires",
            "idade": 65,
            "cpf": "10248897187",
            "rg": "313632728",
            "data_nasc": "21/06/1958",
            "sexo": "Feminino",
            "signo": "Câncer",
            "mae": "Márcia Julia Ayla",
            "pai": "Joaquim Renato Pires",
            "email": "rosangela-pires87@emcinfo.com.br",
            "senha": "DCsNxJyPGi",
            "cep": "69306730",
            "endereco": "Travessa Rio de Janeiro",
            "numero": 215,
            "bairro": "São Pedro",
            "cidade": "Boa Vista",
            "estado": "RR",
            "telefone_fixo": "9527036578",
            "celular": "95994637945",
            "altura": "1,61",
            "peso": 58,
            "tipo_sanguineo": "O-",
            "cor": "verde"
        },
        {
            "nome": "Tânia Catarina Peixoto",
            "idade": 32,
            "cpf": "10100937462",
            "rg": "280641242",
            "data_nasc": "13/03/1991",
            "sexo": "Feminino",
            "signo": "Peixes",
            "mae": "Analu Rosângela Andrea",
            "pai": "Marcos Vinicius Nathan Luís Peixoto",
            "email": "tania.catarina.peixoto@sitran.com.br",
            "senha": "38s21DUwa5",
            "cep": "59135708",
            "endereco": "1ª Travessa do Campo",
            "numero": 874,
            "bairro": "Lagoa Azul",
            "cidade": "Natal",
            "estado": "RN",
            "telefone_fixo": "8439686387",
            "celular": "84991543956",
            "altura": "1,57",
            "peso": 51,
            "tipo_sanguineo": "AB-",
            "cor": "verde"
        },
        {
            "nome": "Joaquim Benedito Otávio Jesus",
            "idade": 20,
            "cpf": "09861805800",
            "rg": "464939574",
            "data_nasc": "01/04/2003",
            "sexo": "Masculino",
            "signo": "Áries",
            "mae": "Gabriela Julia",
            "pai": "Raimundo Diego Jesus",
            "email": "joaquim_jesus@zk.arq.br",
            "senha": "IaqFusK3Fb",
            "cep": "76822248",
            "endereco": "Rua Assis",
            "numero": 723,
            "bairro": "Nova Esperança",
            "cidade": "Porto Velho",
            "estado": "RO",
            "telefone_fixo": "6935753064",
            "celular": "69994580642",
            "altura": "1,64",
            "peso": 56,
            "tipo_sanguineo": "A-",
            "cor": "laranja"
        },
        {
            "nome": "Sueli Letícia Ferreira",
            "idade": 56,
            "cpf": "63091640582",
            "rg": "488531822",
            "data_nasc": "05/02/1967",
            "sexo": "Feminino",
            "signo": "Aquário",
            "mae": "Catarina Nair",
            "pai": "Pietro Ryan Ferreira",
            "email": "suelileticiaferreira@corpus.com.br",
            "senha": "6WI6SKt1g7",
            "cep": "31814970",
            "endereco": "Rua Waldomiro Lobo 851",
            "numero": 871,
            "bairro": "Guarani",
            "cidade": "Belo Horizonte",
            "estado": "MG",
            "telefone_fixo": "3139939472",
            "celular": "31989085702",
            "altura": "1,57",
            "peso": 73,
            "tipo_sanguineo": "AB-",
            "cor": "vermelho"
        },
        {
            "nome": "Vitória Isabella dos Santos",
            "idade": 63,
            "cpf": "17727470414",
            "rg": "223371373",
            "data_nasc": "18/04/1960",
            "sexo": "Feminino",
            "signo": "Áries",
            "mae": "Silvana Eduarda Louise",
            "pai": "Rodrigo Thomas dos Santos",
            "email": "vitoria-dossantos81@pinheiromanaus.com",
            "senha": "QPF5StqYYI",
            "cep": "75101475",
            "endereco": "Rua Delta",
            "numero": 238,
            "bairro": "Setor Summerville",
            "cidade": "Anápolis",
            "estado": "GO",
            "telefone_fixo": "6225037773",
            "celular": "62994099836",
            "altura": "1,60",
            "peso": 64,
            "tipo_sanguineo": "A-",
            "cor": "roxo"
        },
        {
            "nome": "Ana Patrícia Heloisa Ramos",
            "idade": 22,
            "cpf": "07523199810",
            "rg": "494807878",
            "data_nasc": "12/04/2001",
            "sexo": "Feminino",
            "signo": "Áries",
            "mae": "Jennifer Luzia Mariane",
            "pai": "Enzo José Levi Ramos",
            "email": "ana_ramos@lojabichopapao.com.br",
            "senha": "6DG8tONiCx",
            "cep": "74480382",
            "endereco": "Rua VM 4 A",
            "numero": 616,
            "bairro": "Setor Novo Planalto",
            "cidade": "Goiânia",
            "estado": "GO",
            "telefone_fixo": "6225104181",
            "celular": "62986759055",
            "altura": "1,67",
            "peso": 70,
            "tipo_sanguineo": "O+",
            "cor": "amarelo"
        },
        {
            "nome": "Osvaldo Emanuel Manoel Oliveira",
            "idade": 66,
            "cpf": "80849817226",
            "rg": "276097920",
            "data_nasc": "25/04/1957",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Beatriz Lívia Lívia",
            "pai": "Lucca Filipe Oliveira",
            "email": "osvaldoemanueloliveira@andradecamara.com.br",
            "senha": "ickoPnYpNE",
            "cep": "65091248",
            "endereco": "Rua Três Irmãos",
            "numero": 324,
            "bairro": "Vila Maranhão",
            "cidade": "São Luís",
            "estado": "MA",
            "telefone_fixo": "9839597938",
            "celular": "98981063014",
            "altura": "1,84",
            "peso": 104,
            "tipo_sanguineo": "A-",
            "cor": "laranja"
        },
        {
            "nome": "Mário Bernardo Severino Aparício",
            "idade": 66,
            "cpf": "55575960544",
            "rg": "469952246",
            "data_nasc": "05/05/1957",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Simone Josefa",
            "pai": "Manoel Augusto Aparício",
            "email": "mario_aparicio@gameecia.com.br",
            "senha": "3c1mt5bYk2",
            "cep": "84265120",
            "endereco": "Travessa Estocolmo",
            "numero": 142,
            "bairro": "Nossa Senhora do Perpétuo Socorro",
            "cidade": "Telêmaco Borba",
            "estado": "PR",
            "telefone_fixo": "4227231215",
            "celular": "42995355976",
            "altura": "1,91",
            "peso": 63,
            "tipo_sanguineo": "B-",
            "cor": "vermelho"
        },
        {
            "nome": "Flávia Beatriz Aurora Dias",
            "idade": 77,
            "cpf": "55778854501",
            "rg": "245230385",
            "data_nasc": "02/04/1946",
            "sexo": "Feminino",
            "signo": "Áries",
            "mae": "Clarice Sueli Helena",
            "pai": "Noah Enrico Dias",
            "email": "flavia-dias92@vipsaude.com.br",
            "senha": "m6eKQTUAck",
            "cep": "65060630",
            "endereco": "Parque São Luís",
            "numero": 751,
            "bairro": "Aurora",
            "cidade": "São Luís",
            "estado": "MA",
            "telefone_fixo": "9836135518",
            "celular": "98987354435",
            "altura": "1,60",
            "peso": 64,
            "tipo_sanguineo": "B+",
            "cor": "preto"
        }
        , {
            "nome": "Andreia Joana Assunção",
            "idade": 63,
            "cpf": "30285679627",
            "rg": "289882345",
            "data_nasc": "09/05/1960",
            "sexo": "Feminino",
            "signo": "Touro",
            "mae": "Mariah Maria Brenda",
            "pai": "Bryan Pietro Sebastião Assunção",
            "email": "andreiajoanaassuncao@corp.inf.br",
            "senha": "Mo4IWb4wwU",
            "cep": "23095280",
            "endereco": "Praça do Lacio",
            "numero": 191,
            "bairro": "Campo Grande",
            "cidade": "Rio de Janeiro",
            "estado": "RJ",
            "telefone_fixo": "2139233954",
            "celular": "21987790519",
            "altura": "1,54",
            "peso": 79,
            "tipo_sanguineo": "AB-",
            "cor": "verde"
        },
        {
            "nome": "Renan Ian da Mata",
            "idade": 63,
            "cpf": "84408909157",
            "rg": "483745418",
            "data_nasc": "24/04/1960",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Isabelly Nair",
            "pai": "Benedito Rodrigo José da Mata",
            "email": "renan_damata@gilconsultoria.com.br",
            "senha": "IhdhAC4oMK",
            "cep": "79065310",
            "endereco": "Rua Macaba",
            "numero": 937,
            "bairro": "Vila Moreninha III",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6738816131",
            "celular": "67999482577",
            "altura": "1,97",
            "peso": 105,
            "tipo_sanguineo": "B-",
            "cor": "vermelho"
        },
        {
            "nome": "Bento Matheus Enzo de Paula",
            "idade": 34,
            "cpf": "34802710658",
            "rg": "424421689",
            "data_nasc": "17/06/1989",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Brenda Helena Bárbara",
            "pai": "Sérgio Samuel de Paula",
            "email": "bento.matheus.depaula@abcturismo.com.br",
            "senha": "E6J5SYj6AD",
            "cep": "69019630",
            "endereco": "Rua da Amizade",
            "numero": 715,
            "bairro": "Lago Azul",
            "cidade": "Manaus",
            "estado": "AM",
            "telefone_fixo": "9226466217",
            "celular": "92991259305",
            "altura": "1,84",
            "peso": 65,
            "tipo_sanguineo": "B+",
            "cor": "laranja"
        },
        {
            "nome": "Luana Luiza Betina Lopes",
            "idade": 29,
            "cpf": "63182335634",
            "rg": "479347062",
            "data_nasc": "26/05/1994",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Jennifer Evelyn Pietra",
            "pai": "Bryan Mário Eduardo Lopes",
            "email": "luana_lopes@inglesasset.com.br",
            "senha": "pyfZ7SsJm8",
            "cep": "83085395",
            "endereco": "Rua José Augusto Fialho",
            "numero": 185,
            "bairro": "Quississana",
            "cidade": "São José dos Pinhais",
            "estado": "PR",
            "telefone_fixo": "4127738306",
            "celular": "41993124926",
            "altura": "1,63",
            "peso": 62,
            "tipo_sanguineo": "B-",
            "cor": "preto"
        },
        {
            "nome": "Sueli Marlene das Neves",
            "idade": 26,
            "cpf": "20298787407",
            "rg": "180710047",
            "data_nasc": "02/06/1997",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Ester Maitê Jéssica",
            "pai": "Raul Ruan Márcio das Neves",
            "email": "sueli.marlene.dasneves@a.com",
            "senha": "BGxEeXewEU",
            "cep": "79091690",
            "endereco": "Rua Luiz Ribeiro Pires",
            "numero": 994,
            "bairro": "Parque Residencial União",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6728572265",
            "celular": "67985816217",
            "altura": "1,85",
            "peso": 52,
            "tipo_sanguineo": "B-",
            "cor": "preto"
        },
        {
            "nome": "Oliver Caleb Farias",
            "idade": 65,
            "cpf": "04499258626",
            "rg": "320221039",
            "data_nasc": "17/04/1958",
            "sexo": "Masculino",
            "signo": "Áries",
            "mae": "Josefa Bianca",
            "pai": "Pietro Daniel Augusto Farias",
            "email": "oliver_caleb_farias@flexchange.com.br",
            "senha": "z0ALFrzmXF",
            "cep": "77826105",
            "endereco": "Rua 15",
            "numero": 558,
            "bairro": "Loteamento Barros",
            "cidade": "Araguaína",
            "estado": "TO",
            "telefone_fixo": "6335273304",
            "celular": "63993916112",
            "altura": "1,93",
            "peso": 104,
            "tipo_sanguineo": "B-",
            "cor": "vermelho"
        },
        {
            "nome": "Yasmin Priscila Aurora Souza",
            "idade": 23,
            "cpf": "59801753340",
            "rg": "364076537",
            "data_nasc": "13/01/2000",
            "sexo": "Feminino",
            "signo": "Capricórnio",
            "mae": "Daiane Antônia",
            "pai": "Roberto Severino Souza",
            "email": "yasmin-souza93@contabilidaderangel.com.br",
            "senha": "iZ47K5ODfS",
            "cep": "76965746",
            "endereco": "Rua Rio Negro",
            "numero": 400,
            "bairro": "Floresta",
            "cidade": "Cacoal",
            "estado": "RO",
            "telefone_fixo": "6926998418",
            "celular": "69985704316",
            "altura": "1,66",
            "peso": 52,
            "tipo_sanguineo": "B+",
            "cor": "amarelo"
        },
        {
            "nome": "Severino Danilo da Cruz",
            "idade": 36,
            "cpf": "25752298121",
            "rg": "257697135",
            "data_nasc": "02/03/1987",
            "sexo": "Masculino",
            "signo": "Peixes",
            "mae": "Sophia Evelyn Clara",
            "pai": "Gael Isaac Gael da Cruz",
            "email": "severino_danilo_dacruz@construtoracostanorte.com.br",
            "senha": "fZ671g7Nwg",
            "cep": "58406820",
            "endereco": "Rua Geni Barbosa Ferreira",
            "numero": 315,
            "bairro": "Nova Brasília",
            "cidade": "Campina Grande",
            "estado": "PB",
            "telefone_fixo": "8336672851",
            "celular": "83988372175",
            "altura": "1,82",
            "peso": 73,
            "tipo_sanguineo": "O-",
            "cor": "amarelo"
        },
        {
            "nome": "Jorge André Lucas Nascimento",
            "idade": 77,
            "cpf": "54092120613",
            "rg": "398669879",
            "data_nasc": "19/06/1946",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Sara Maitê Lorena",
            "pai": "Vinicius Arthur Nascimento",
            "email": "jorge.andre.nascimento@kframe.com.br",
            "senha": "cJ1Msy3sdr",
            "cep": "79037073",
            "endereco": "Rua Marcial",
            "numero": 809,
            "bairro": "Jardim Veraneio",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6736036997",
            "celular": "67992652208",
            "altura": "1,81",
            "peso": 56,
            "tipo_sanguineo": "B+",
            "cor": "amarelo"
        },
        {
            "nome": "Nicolas Fábio Ferreira",
            "idade": 48,
            "cpf": "40892589361",
            "rg": "248497959",
            "data_nasc": "05/01/1975",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Sabrina Isis",
            "pai": "Kevin Vicente Noah Ferreira",
            "email": "nicolas.fabio.ferreira@edwardmaluf.com.br",
            "senha": "Ajg3wAisXZ",
            "cep": "73808622",
            "endereco": "Rua Gameleira",
            "numero": 162,
            "bairro": "Jardim Ipê",
            "cidade": "Formosa",
            "estado": "GO",
            "telefone_fixo": "6125036675",
            "celular": "61981941545",
            "altura": "1,88",
            "peso": 74,
            "tipo_sanguineo": "O+",
            "cor": "amarelo"
        },
        {
            "nome": "Leandro Danilo Lucca Cardoso",
            "idade": 54,
            "cpf": "42637497238",
            "rg": "189808299",
            "data_nasc": "27/06/1969",
            "sexo": "Masculino",
            "signo": "Câncer",
            "mae": "Vitória Catarina",
            "pai": "Heitor Renan Cardoso",
            "email": "leandro_danilo_cardoso@terrabrasil.com.br",
            "senha": "W7HBh99x4E",
            "cep": "68900033",
            "endereco": "Passagem José Serra e Silva",
            "numero": 674,
            "bairro": "Central",
            "cidade": "Macapá",
            "estado": "AP",
            "telefone_fixo": "9637488208",
            "celular": "96984664858",
            "altura": "1,68",
            "peso": 54,
            "tipo_sanguineo": "B-",
            "cor": "laranja"
        },
        {
            "nome": "Sophie Rosângela Teixeira",
            "idade": 25,
            "cpf": "43828338763",
            "rg": "130956983",
            "data_nasc": "03/02/1998",
            "sexo": "Feminino",
            "signo": "Aquário",
            "mae": "Cristiane Raimunda Malu",
            "pai": "Breno Theo Teixeira",
            "email": "sophie_teixeira@solucao.adm.br",
            "senha": "UxumgdtUGP",
            "cep": "58063090",
            "endereco": "Rua Antônio Belarmino da Costa",
            "numero": 933,
            "bairro": "Valentina de Figueiredo",
            "cidade": "João Pessoa",
            "estado": "PB",
            "telefone_fixo": "8338439910",
            "celular": "83988755734",
            "altura": "1,75",
            "peso": 52,
            "tipo_sanguineo": "AB-",
            "cor": "preto"
        },
        {
            "nome": "Luna Sophia Eduarda dos Santos",
            "idade": 58,
            "cpf": "72669389619",
            "rg": "399556436",
            "data_nasc": "13/02/1965",
            "sexo": "Feminino",
            "signo": "Aquário",
            "mae": "Giovana Débora Isis",
            "pai": "Gabriel Kauê dos Santos",
            "email": "luna-dossantos89@salvagninigroup.com",
            "senha": "8kZIO4IK2r",
            "cep": "30510330",
            "endereco": "Rua Magalhães Pinto",
            "numero": 304,
            "bairro": "Nova Gameleira",
            "cidade": "Belo Horizonte",
            "estado": "MG",
            "telefone_fixo": "3137061682",
            "celular": "31982039574",
            "altura": "1,78",
            "peso": 52,
            "tipo_sanguineo": "AB+",
            "cor": "preto"
        },
        {
            "nome": "Davi Gabriel Gael da Rosa",
            "idade": 39,
            "cpf": "82593318376",
            "rg": "440245254",
            "data_nasc": "26/02/1984",
            "sexo": "Masculino",
            "signo": "Peixes",
            "mae": "Mariane Bárbara",
            "pai": "Danilo Edson Iago da Rosa",
            "email": "davi.gabriel.darosa@belaggiovini.com.br",
            "senha": "WzzRSD028z",
            "cep": "79824318",
            "endereco": "Rua Paineira",
            "numero": 888,
            "bairro": "Ecoville",
            "cidade": "Dourados",
            "estado": "MS",
            "telefone_fixo": "6736837604",
            "celular": "67997087114",
            "altura": "1,88",
            "peso": 64,
            "tipo_sanguineo": "B+",
            "cor": "laranja"
        },
        {
            "nome": "Marlene Kamilly da Rocha",
            "idade": 66,
            "cpf": "02431878155",
            "rg": "182110205",
            "data_nasc": "16/05/1957",
            "sexo": "Feminino",
            "signo": "Touro",
            "mae": "Benedita Luzia Elaine",
            "pai": "Diego Filipe da Rocha",
            "email": "marlene.kamilly.darocha@ogn.com.br",
            "senha": "3i5uE38RIK",
            "cep": "74630210",
            "endereco": "Rua L 4",
            "numero": 626,
            "bairro": "Feliz",
            "cidade": "Goiânia",
            "estado": "GO",
            "telefone_fixo": "6229481041",
            "celular": "62987766501",
            "altura": "1,75",
            "peso": 50,
            "tipo_sanguineo": "AB-",
            "cor": "vermelho"
        },
        {
            "nome": "César Cauê Ribeiro",
            "idade": 25,
            "cpf": "47787369078",
            "rg": "231869241",
            "data_nasc": "21/06/1998",
            "sexo": "Masculino",
            "signo": "Câncer",
            "mae": "Ester Lúcia",
            "pai": "Arthur Francisco Vinicius Ribeiro",
            "email": "cesar_caue_ribeiro@ovale.com.br",
            "senha": "bewrXk5Pdb",
            "cep": "94836080",
            "endereco": "Rua Dário Pederneiras",
            "numero": 883,
            "bairro": "Tijuca",
            "cidade": "Alvorada",
            "estado": "RS",
            "telefone_fixo": "5137813657",
            "celular": "51986228321",
            "altura": "1,96",
            "peso": 72,
            "tipo_sanguineo": "AB-",
            "cor": "laranja"
        },
        {
            "nome": "Pietra Marlene Assis",
            "idade": 31,
            "cpf": "33011958572",
            "rg": "147222412",
            "data_nasc": "14/01/1992",
            "sexo": "Feminino",
            "signo": "Capricórnio",
            "mae": "Renata Carla Sueli",
            "pai": "Gabriel Carlos André Assis",
            "email": "pietra_assis@andressamelo.com.br",
            "senha": "p9f8tBdnZN",
            "cep": "29142480",
            "endereco": "Rua Vicente Rebolli",
            "numero": 516,
            "bairro": "Vila Isabel",
            "cidade": "Cariacica",
            "estado": "ES",
            "telefone_fixo": "2738517489",
            "celular": "27991383000",
            "altura": "1,54",
            "peso": 69,
            "tipo_sanguineo": "O-",
            "cor": "laranja"
        },
        {
            "nome": "Miguel Matheus Aragão",
            "idade": 34,
            "cpf": "98930771769",
            "rg": "229052678",
            "data_nasc": "09/01/1989",
            "sexo": "Masculino",
            "signo": "Capricórnio",
            "mae": "Olivia Ayla Evelyn",
            "pai": "Pietro Erick Aragão",
            "email": "miguel-aragao75@r7.com.br",
            "senha": "ySQS6IalpN",
            "cep": "68907400",
            "endereco": "Alameda Tróia",
            "numero": 583,
            "bairro": "Renascer",
            "cidade": "Macapá",
            "estado": "AP",
            "telefone_fixo": "9625708271",
            "celular": "96999905080",
            "altura": "1,63",
            "peso": 55,
            "tipo_sanguineo": "A+",
            "cor": "amarelo"
        },
        {
            "nome": "Samuel Nathan Ramos",
            "idade": 33,
            "cpf": "19698195882",
            "rg": "176077248",
            "data_nasc": "15/03/1990",
            "sexo": "Masculino",
            "signo": "Peixes",
            "mae": "Joana Marcela Alice",
            "pai": "Carlos Eduardo Vitor Ramos",
            "email": "samuel_nathan_ramos@etec.sp.gov.br",
            "senha": "xenrBhtx7B",
            "cep": "69906098",
            "endereco": "Travessa Janaína",
            "numero": 828,
            "bairro": "Areal",
            "cidade": "Rio Branco",
            "estado": "AC",
            "telefone_fixo": "6828280913",
            "celular": "68993258217",
            "altura": "1,97",
            "peso": 68,
            "tipo_sanguineo": "B+",
            "cor": "vermelho"
        },
        {
            "nome": "Antonella Rayssa Helena Melo",
            "idade": 72,
            "cpf": "43991421208",
            "rg": "105510683",
            "data_nasc": "06/01/1951",
            "sexo": "Feminino",
            "signo": "Capricórnio",
            "mae": "Rebeca Heloise Sebastiana",
            "pai": "Pietro Vinicius Melo",
            "email": "antonella-melo99@roche.com",
            "senha": "MAcKEB2hdx",
            "cep": "88352127",
            "endereco": "Rua SR - 009",
            "numero": 560,
            "bairro": "Santa Rita",
            "cidade": "Brusque",
            "estado": "SC",
            "telefone_fixo": "4737884780",
            "celular": "47988429783",
            "altura": "1,55",
            "peso": 46,
            "tipo_sanguineo": "AB+",
            "cor": "vermelho"
        },
        {
            "nome": "Raimundo Bruno Costa",
            "idade": 79,
            "cpf": "17313244649",
            "rg": "275950451",
            "data_nasc": "23/04/1944",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Laís Luiza",
            "pai": "Bryan Tiago Vitor Costa",
            "email": "raimundo-costa71@hotmmail.com",
            "senha": "Ki4LfZdfIZ",
            "cep": "35930682",
            "endereco": "Rua Odilon Bicalho",
            "numero": 214,
            "bairro": "JK",
            "cidade": "João Monlevade",
            "estado": "MG",
            "telefone_fixo": "3125207085",
            "celular": "31993657049",
            "altura": "1,62",
            "peso": 70,
            "tipo_sanguineo": "A+",
            "cor": "roxo"
        },
        {
            "nome": "Olivia Rosa Nunes",
            "idade": 22,
            "cpf": "92060751608",
            "rg": "349773336",
            "data_nasc": "22/01/2001",
            "sexo": "Feminino",
            "signo": "Aquário",
            "mae": "Alessandra Isabelle",
            "pai": "Arthur Manoel Nunes",
            "email": "olivia_rosa_nunes@htomail.com",
            "senha": "ZRU1HNiu0g",
            "cep": "49060610",
            "endereco": "Rua Manoel Preto",
            "numero": 407,
            "bairro": "Santo Antônio",
            "cidade": "Aracaju",
            "estado": "SE",
            "telefone_fixo": "7928988149",
            "celular": "79999512316",
            "altura": "1,55",
            "peso": 49,
            "tipo_sanguineo": "B-",
            "cor": "laranja"
        },
        {
            "nome": "Carlos Thiago Roberto Baptista",
            "idade": 26,
            "cpf": "43942999692",
            "rg": "236185950",
            "data_nasc": "26/05/1997",
            "sexo": "Masculino",
            "signo": "Gêmeos",
            "mae": "Malu Maria Luzia",
            "pai": "Anderson Carlos Baptista",
            "email": "carlosthiagobaptista@right.com.br",
            "senha": "dk6YbWy4dt",
            "cep": "95084230",
            "endereco": "Rua Dom Antônio Passaggi",
            "numero": 655,
            "bairro": "Exposição",
            "cidade": "Caxias do Sul",
            "estado": "RS",
            "telefone_fixo": "5437127443",
            "celular": "54997200087",
            "altura": "1,72",
            "peso": 69,
            "tipo_sanguineo": "O+",
            "cor": "roxo"
        },
        {
            "nome": "Caroline Yasmin Sales",
            "idade": 26,
            "cpf": "07390230398",
            "rg": "488754331",
            "data_nasc": "26/02/1997",
            "sexo": "Feminino",
            "signo": "Peixes",
            "mae": "Mirella Daiane Eloá",
            "pai": "Luiz Benedito Ruan Sales",
            "email": "carolineyasminsales@mectron.com.br",
            "senha": "4CUGXrnes7",
            "cep": "57306190",
            "endereco": "Rua Estudante Martha Régia Bispo",
            "numero": 718,
            "bairro": "Eldorado",
            "cidade": "Arapiraca",
            "estado": "AL",
            "telefone_fixo": "8235354156",
            "celular": "82993904349",
            "altura": "1,78",
            "peso": 74,
            "tipo_sanguineo": "B-",
            "cor": "laranja"
        },
        {
            "nome": "Cauã Cauã Victor Barbosa",
            "idade": 53,
            "cpf": "11180065859",
            "rg": "138983525",
            "data_nasc": "14/02/1970",
            "sexo": "Masculino",
            "signo": "Aquário",
            "mae": "Aline Sophie Eloá",
            "pai": "Leandro Matheus Barbosa",
            "email": "caua.caua.barbosa@saboia.me",
            "senha": "8hoHmYkMUN",
            "cep": "68909835",
            "endereco": "Avenida Zelia Cardoso de Melo",
            "numero": 284,
            "bairro": "Novo Horizonte",
            "cidade": "Macapá",
            "estado": "AP",
            "telefone_fixo": "9637203525",
            "celular": "96987234180",
            "altura": "1,99",
            "peso": 95,
            "tipo_sanguineo": "O-",
            "cor": "vermelho"
        },
        {
            "nome": "Renata Sophie Lívia Cavalcanti",
            "idade": 68,
            "cpf": "64762896322",
            "rg": "115246009",
            "data_nasc": "24/05/1955",
            "sexo": "Feminino",
            "signo": "Gêmeos",
            "mae": "Luna Lúcia",
            "pai": "Isaac Leonardo Yuri Cavalcanti",
            "email": "renatasophiecavalcanti@eyejoy.com.br",
            "senha": "ZnBGmoyJto",
            "cep": "49048110",
            "endereco": "Rua Doutor Carlos Alberto Rolla",
            "numero": 340,
            "bairro": "Luzia",
            "cidade": "Aracaju",
            "estado": "SE",
            "telefone_fixo": "7928803698",
            "celular": "79986568274",
            "altura": "1,65",
            "peso": 49,
            "tipo_sanguineo": "AB+",
            "cor": "vermelho"
        },
        {
            "nome": "Nelson Mário Heitor Moraes",
            "idade": 28,
            "cpf": "58576169649",
            "rg": "507121363",
            "data_nasc": "25/06/1995",
            "sexo": "Masculino",
            "signo": "Câncer",
            "mae": "Gabriela Olivia Maria",
            "pai": "Rodrigo Otávio Moraes",
            "email": "nelson_moraes@elevaconsultancy.com.br",
            "senha": "FJqAWdNwfq",
            "cep": "91520655",
            "endereco": "Rua Três Mil Setecentos e Vinte e Sete",
            "numero": 748,
            "bairro": "São José",
            "cidade": "Porto Alegre",
            "estado": "RS",
            "telefone_fixo": "5138099294",
            "celular": "51986944023",
            "altura": "1,89",
            "peso": 59,
            "tipo_sanguineo": "B-",
            "cor": "vermelho"
        },
        {
            "nome": "Luzia Evelyn Kamilly Moura",
            "idade": 65,
            "cpf": "26838687070",
            "rg": "219782945",
            "data_nasc": "09/04/1958",
            "sexo": "Feminino",
            "signo": "Áries",
            "mae": "Isabel Sara",
            "pai": "Thomas Ryan Moura",
            "email": "luzia_moura@serteccontabil.com.br",
            "senha": "OgCKwPcrzw",
            "cep": "79110310",
            "endereco": "Rua Carmela Dutra",
            "numero": 635,
            "bairro": "Sobrinho",
            "cidade": "Campo Grande",
            "estado": "MS",
            "telefone_fixo": "6737447391",
            "celular": "67982193515",
            "altura": "1,66",
            "peso": 53,
            "tipo_sanguineo": "AB-",
            "cor": "verde"
        },
        {
            "nome": "Vicente Filipe Vinicius Freitas",
            "idade": 37,
            "cpf": "88973996061",
            "rg": "328236640",
            "data_nasc": "22/04/1986",
            "sexo": "Masculino",
            "signo": "Touro",
            "mae": "Simone Emanuelly Betina",
            "pai": "Pedro Henrique Osvaldo Freitas",
            "email": "vicente_filipe_freitas@fabiooliva.com.br",
            "senha": "KKrrRNrWE2",
            "cep": "68928136",
            "endereco": "Alameda Tambaú",
            "numero": 718,
            "bairro": "Fonte Nova",
            "cidade": "Santana",
            "estado": "AP",
            "telefone_fixo": "9635138137",
            "celular": "96989730996",
            "altura": "1,88",
            "peso": 71,
            "tipo_sanguineo": "B-",
            "cor": "vermelho"
        },
        {
            "nome": "Helena Melissa Gomes",
            "idade": 40,
            "cpf": "40107172976",
            "rg": "292674442",
            "data_nasc": "08/04/1983",
            "sexo": "Feminino",
            "signo": "Áries",
            "mae": "Vera Simone Sônia",
            "pai": "Julio Tomás Gomes",
            "email": "helena_melissa_gomes@geometrabte.com.br",
            "senha": "BU5Jtiftwy",
            "cep": "31255100",
            "endereco": "Rua Leiria",
            "numero": 772,
            "bairro": "São Francisco",
            "cidade": "Belo Horizonte",
            "estado": "MG",
            "telefone_fixo": "3138185980",
            "celular": "31987707567",
            "altura": "1,73",
            "peso": 52,
            "tipo_sanguineo": "O+",
            "cor": "preto"
        }
    ]

module.exports = {
    users
}

